(in-package #:pm.worker)

(defclass database-interface ()
  ((db-type)
   (db-host)
   (db-port)
   (db-user)
   (db-pass)
   (db-name)))

(defgeneric find-matching (database-interface user))
(defgeneric add-user (database-interface user))
(defgeneric del-user (database-interface user))
(defgeneric add-group (database-interface group))
(defgeneric del-group (database-interface group))
(defgeneric add-user-to-group (database-interface user group))
(defgeneric del-user-from-group (database-interface user group))
(defgeneric reset-password (database-interface user))
(defgeneric change-password (database-interface user))
(defgeneric change-user-data (database-interface user))
(defgeneric add-relationship (database-interface relationship))
(defgeneric fetch-user-notifications (database-interface user))

(defclass relationship ()
  ((id)
   (left-side)
   (right-side)
   (type)))

(defgeneric add-to-left (relationship user))
(defgeneric add-to-right (relationship user))
(defgeneric delete-member (relationship user))
(defgeneric delete-relationship (relationship))
(defgeneric change-relationship (relationship))

(defclass group ()
  ((id)
   (name)
   (members)
   (tags)))

(defgeneric add-member (group user))
(defgeneric delete-member (group user))
(defgeneric change-group (group))
(defgeneric delete-group (group))

(defclass user ()
  ((id)
   (first-name)
   (second-name)
   (sex)
   (birth-date)
   (tags)))

(defgeneric change-user (user))
(defgeneric delete-user (user))
